config/routes.rb
Rails.application.routes.draw do
  resource :login,   controller: :login,   only: [:new, :create, :destroy]
  resource :welcome, controller: :welcome, only: [:show]

  concern :article do
    post :comment, on: :collection
    put  :search,  on: :collection
  end

  concern :mail do
    get :announce , on: :collection
    get :finish, on: :collection
  end

  resources :skill_profiles, concerns: :article
  resources :settings, only: [:edit, :update]
  resources :admin, only: [:index, :create] do
    get :login, on: :collection
  end
  resource  :reset_password, concerns: :mail

  get  '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/logical/skill_profile.rb
require 'las_errors'

class SkillProfile < ActiveRecord::Base
  include RelationSkillProfile

  scope :latest, ->(list_num = Settings.skill_profile.show_list.max_num) {
    order('created_at DESC').limit(list_num)
  }

  class << self
    def submit(params, user_id)
      skill_profile = SkillProfile.new(title: params[:title], user_id: user_id)
      if skill_profile.save
        begin
          skill_profile.create_article(title: params[:title], content: params[:content], written_style: skill_profile.user.write_style)
        rescue ActiveRecord::StatementInvalid
          skill_profile.delete
          raise ValidationError, 'Detect All Validation'
        end
      else
        raise ValidationError, active_model_errors_to_string(profile)
      end
    end

    def rewrite(params, current_user)
      begin
        @errors = []
        validate_skill_profile_edit(params)
        raise ValidationError Error.join(@errors) if @errors.present?
        # written_style saving is needed at this time
        current_user.skill_profile.article.update_attributes!(content: params[:content], written_style: current_user.write_style)
      end
    end

    def search(params)
      params_search_key = Settings.skill_profile.form.object.search.to_sym
      found_records = Search::Word.reg_exp(Article.where.not(skill_profile_id: nil), :content, params[params_search_key])
      return [] if found_records.blank?
      found_records.map { |record| record.skill_profile }
    end

    def format_error_message(error_message)
      error_message.split(Settings[:error][:seperate])
    end

    private

    def active_model_errors_to_string(errored_model_obj)
      errored_model_obj.errors.messages.values.flatten.join(Settings[:error][:seperate])
    end
  end
end

app/controllers/skill_profiles_controller.rb
class SkillProfilesController < ApplicationController
  include SessionAction
  before_action :session_required
  before_action :set_article,      only: [:show, :edit, :update]
  before_action :authorize_edit,   only: [:edit, :update]

  def index
    @profiles = SkillProfile.latest
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    begin
      SkillProfile.submit(article_params, session[:id])
      redirect_to skill_profiles_url
    rescue ValidationError => e
      flash.now[:alert] = SkillProfile.format_error_message(e.message)
      render :new
    end
  end

  def update
    begin
      SkillProfile.rewrite(article_params, current_user)
      redirect_to skill_profiles_url
    rescue ValidationError => e
      flash.now[:alert] = SkillProfile.format_error_message(e.message)
      render :edit
    end
  end

  def comment
    begin
      return render_403 unless Cert::Params.numeric?(params[:article_id])
      @article = Article.find_by(id: params[:article_id]) # @article is used to #show view
      Comment.submit(comment_params, params[:article_id], session[:id])
    rescue ValidationError => e
      flash.now[:alert] = Flash.format_error_message(e.message)
    end
    render :show
  end

  def search
    @profiles = SkillProfile.search(params)
    render :index
  end

  private

  def set_article
    return render_404 unless Cert::Params.numeric?(params[:id])
    @article = SkillProfile.find_by(id: params[:id]).article
  end

  def authorize_edit
    unless @article.skill_profile.user_id == session[:id]
      render_403
    end
  end

  def article_params 
    params.require(:article).permit(:title, :content)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/skill_profiles_helper.rb
module SkillProfilesHelper
end

app/views/skill_profiles/edit.html.haml
- if alert.present?
  #error_message
    %div
      - alert.each do |message|
        %li
          = message

%div.col-lg-6
  %div.well.bs-component
    = form_for(:article, {url: skill_profile_url, method: :put, id: @article.id, html: {class: 'form-horizontal'}}) do |f|
      %div
        = label_tag :content, t('las.skill_profiles.content')
        = f.text_area :content, value: @article.content.html_safe
      %div
        = submit_tag t('las.skill_profiles.update')

= link_to 'Back', skill_profiles_path

app/views/skill_profiles/index.html.haml
= content_for(:title, t('las.skill_profile.index.title'))

= form_tag(search_skill_profiles_url, method: :put) do
  %div.search_content
    = label_tag :search, t('las.skill_profile.label.search')
    = text_field_tag Settings.skill_profile.form.object.search
  %div.submit_content
    = submit_tag t('las.skill_profile.button.search')

%table
  - if @profiles.present?
    %thead
      %tr
        %th{colspan: '3'}
        %th= t('las.skill_profile.label.name')
        %th= t('las.skill_profile.label.comment')
        %th{colspan: '3'}
    %tbody
      - @profiles.each do |profile|
        %tr
          %td{colspan: '3'}
          %td
            = link_to profile.user.name, skill_profile_path(id: profile.article.id)
            - if profile.user.avatar?
              = image_tag profile.user.avatar.thumb.url
            - else
              %i.icon-user
          %td= announce_comment(profile.article.id)
          %td{colspan: '3'}
  - else
    %div.message.not_exist
      = t('las.skill_profile.message.article.not_exist')

= link_to t('las.skill_profile.link.welcome'), welcome_path

app/views/skill_profiles/new.html.haml
- if alert.present?
  #error_message
    %div
      - alert.each do |message|
        %li
          = message

= form_for(:article, url: skill_profiles_path) do |f|
  %div
    = f.label :title, t('las.skill_profiles.title')
    = f.text_field :title

  %div
    = f.label :content, t('las.skill_profiles.content')
    = f.text_area :content
  = f.submit t('las.skill_profiles.submit')

= link_to 'Back', skill_profiles_path

app/views/skill_profiles/show.html.haml
= javascript_include_tag 'skill_profiles'

= content_for(:title, t('las.skill_profile.show.title') + @article.skill_profile.user.name)

#alert
  - if alert
    %ul
      - alert.each do |message|
        %li
          = message


- if @article.skill_profile.user.id == session[:id]
  = link_to t('las.skill_profile.link.edit'), edit_skill_profile_path(id: @article.id)

%div.title_description
  = @article.skill_profile.user.name
%div.content_description
  - case @article.written_style
  - when Settings.user.write_style.plain
    = @article.content
  - when Settings.user.write_style.md
    = markdown_to_html(@article.content)

%div.comment_description
  - Comment.show_all(@article.id).each do |comment|
    %ul
      %li
        = comment.content

= form_for(:comment, url: comment_skill_profiles_path(article_id: @article.id)) do |form|
  %div#comment_description
    %div.content_description
      = form.label :content, t('las.skill_profile.label.comment')
      = form.text_area :content
    %div.submit_field
      = form.submit t('las.skill_profile.button.submit')

= link_to t('las.skill_profile.link.index'), skill_profiles_path