config/routes.rb
Rails.application.routes.draw do
  resource :login,   controller: :login,   only: [:new, :create, :destroy]
  resource :welcome, controller: :welcome, only: [:show]

  concern :article do
    post :comment, on: :collection
    put  :search,  on: :collection
  end

  concern :mail do
    get :announce , on: :collection
    get :finish, on: :collection
  end

  resources :skill_profiles, concerns: :article
  resources :settings, only: [:edit, :update]
  resources :admin, only: [:index, :create] do
    get :login, on: :collection
  end
  resource  :reset_password, concerns: :mail

  get  '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/logical/setting.rb
class Setting
  class << self
    # Refactorable?
    # def update_setting(column, user_id, params)
    #   user = User.find_by_id(user_id)
    #   user.send(#{column}) = params
    #   user.save!
    # end
    def password_update(user_id, password, password_confirmation)
      user = User.find_by_id(user_id)
      user.update({password: password, password_confirmation: password_confirmation})
    end

    def avatar_update(user_id, avatar)
      user        = User.find_by_id(user_id)
      user.avatar = avatar
      user.save!
    end

    def write_style_update(user_id, write_style)
      user             = User.find_by_id(user_id)
      user.write_style = write_style
      user.save!
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  include SessionAction
  before_action :session_required
  before_action :prohibit_editing_other, only: [:edit]
  before_action :set_user, only: [:edit]

  def edit
    @tab = 'password'
  end

  def update
    @tab = params[:tab]
    begin
      User.update_settings(settings_params, params[:id], @tab)
    rescue ValidationError => e
      flash.now[:alert] = User.format_error_message(e.message)
      return render 'edit'
    end
    flash.now[:notice] = I18n.t("las.settings.message.notice.updated.#{@tab}")
    render 'edit'
  end

  private

  def settings_params
    params.permit(:current_password, :password, :password_confirmation, :write_style, :avatar)
  end

  def prohibit_editing_other
    if session[:id] != params[:id].to_i
      render 'edit'
    end
  end

  def set_user
    @user = User.find_by_id(session[:id])
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
  def tab_group
    Settings[:settings][:tab][:group]
  end

  def activate_if_same(judge_base, obj)
    judge_base == obj ? 'active' : nil
  end

  def precheck_radio_tag_if_setting_activate(name, type)
    radio_button_tag name, type, (true if current_user.write_style == type)
  end
end

app/views/settings/edit.html.haml
= javascript_include_tag 'settings'

= content_for(:title, t('las.settings.title'))

%div#tab
  - tab_group.each do |tab_name|
    %div{class: tab_name}
      = js_void_link_to(tab_name)

%div#notice
  - if notice
    = notice

%div#alert
  - if alert
    - alert.each do |message|
      %li
        = message

%div#setting
  %div.password.area{class: activate_if_same(@tab, 'password')}
    = form_tag(setting_path(tab: 'password'), method: :put) do
      %div.current_password
        = label_tag :current_password, 'current_password'
        = password_field_tag :current_password
      %div.password
        = label_tag :password, 'password'
        = password_field_tag :password
      %div.password_confirmation_
        = label_tag :password_confirmation, 'password_confirmation'
        = password_field_tag :password_confirmation
      %div.submit
        = submit_tag 'update'
  %div.avatar.area{class: activate_if_same(@tab, 'avatar')}
    - if current_user.avatar?
      = image_tag current_user.avatar.profile.url
    - else
      %i.icon-user
    = form_tag(setting_path(tab: 'avatar'), multipart: true, method: :put) do |f|
      %div.avatar
        = label_tag :avatar, 'avatar'
        = file_field_tag :avatar
      %div.submit
        = submit_tag 'update'
  %div.write_style.area{class: activate_if_same(@tab, 'write_style')}
    = form_tag(setting_path(tab: 'write_style'), method: :put) do
      %div.text_plain
        = label_tag :text_plain, 'text_plain'
        = precheck_radio_tag_if_setting_activate('write_style', Settings[:user][:write_style][:plain])
      %div.markdown
        = label_tag :markdown, 'markdown'
        = precheck_radio_tag_if_setting_activate('write_style', Settings[:user][:write_style][:md])
      %div.submit
        = submit_tag 'update'