config/routes.rb
Rails.application.routes.draw do
  resource :login,   controller: :login,   only: [:new, :create, :destroy]
  resource :welcome, controller: :welcome, only: [:show]

  concern :article do
    post :comment, on: :collection
    put  :search,  on: :collection
  end

  concern :mail do
    get :announce , on: :collection
    get :finish, on: :collection
  end

  resources :skill_profiles, concerns: :article
  resources :settings, only: [:edit, :update]
  resources :admin, only: [:index, :create] do
    get :login, on: :collection
  end
  resource  :reset_password, concerns: :mail

  get  '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/logical/reset_password.rb
class ResetPassword < ActiveRecord::Base
  include RelationResetPassword

  class << self
    def reset_token(token)
      reset_password = find_by_token(token)
      reset_password.token = nil
      reset_password.save!
    end
  end
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  before_action :back_to_root,    only: [:new]
  before_action :edit_forbidden,  only: [:edit]
  before_action :render_fobidden, only: [:announce, :finish]

  def new
  end

  def create
    begin
      User.request_reset_password(params)
      flash.now[:notice] = I18n.t('las.reset_password.message.notice.send_email')
      render 'announce'
    rescue ValidationError => e
      flash.now[:alert] = User.format_error_message(e.message)
      render 'new'
    end
  end

  def edit
    begin
      # use at form
      User.certificate(params[:format])
    rescue ActiveRecord::RecordNotFound, CertificationError => e
      flash.now[:alert] = [I18n.t('las.reset_password.message.alert.certification')]
      render 'announce'
    end
  end

  def update
    begin
      User.reset_password(params[:format], reset_password_params)
      ResetPassword.reset_token(params[:format])
      flash.now[:notice] = I18n.t('las.reset_password.message.notice.success_update')
      render 'finish'
    rescue ValidationError => e
      flash.now[:alert] = User.format_error_message(e.message)
      render 'edit'
    end
  end

  def announce
  end

  def finish
  end

  private

  def reset_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def back_to_root
    redirect_to root_path if session[:id]
  end

  def edit_forbidden
    raise Forbidden if params[:format].blank?
  end

  def render_fobidden
    raise Forbidden if request
  end

end

app/views/reset_passwords/announce.html.haml
%div#notice
  - if notice
    = notice

%div#alert
  - if alert
    - alert.each do |message|
      = message

= link_to 'reset_password', new_reset_password_path
= link_to 'login', login_path

app/views/reset_passwords/edit.html.haml
= content_for :title, t('las.reset_password.title')

%div#alert
  - if alert
    - alert.each do |message|
      = message

%div
  = form_for(ResetPassword.find_by_token(params[:format]).user, url: reset_password_url(params[:format])) do |f|
    %div
      = f.label :password, 'password'
      = f.password_field :password, class: 'form-control'
    %div
      = f.label :password_confirmation, 'password_confirmation'
      = f.password_field :password_confirmation
    %div
      = f.submit 'submit'

app/views/reset_passwords/finish.html.haml
Finished!

app/views/reset_passwords/new.html.haml
= content_for :title, t('las.reset_password.title')

= javascript_include_tag 'reset_password'

%div#alert
  - if alert
    - alert.each do |message|
      = message

= form_tag(reset_password_url) do
  %div#email_content
    = label_tag :email, 'email'
    = text_field_tag :email
  %div#submit_content
    = submit_tag 'submit'